//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIEntity : DbContext
    {
        public BIEntity()
            : base("name=BIEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PCIDtoStationMap> PCIDtoStationMaps { get; set; }
        public virtual DbSet<COFFEE_PROD_CAT> COFFEE_PROD_CAT { get; set; }
        public virtual DbSet<COMMONS_LOCATIONS> COMMONS_LOCATIONS { get; set; }
        public virtual DbSet<DATE> DATES { get; set; }
        public virtual DbSet<ESPRESSO_TERMINALS> ESPRESSO_TERMINALS { get; set; }
        public virtual DbSet<LOCATION> LOCATIONS { get; set; }
        public virtual DbSet<MasterBuildingList> MasterBuildingLists { get; set; }
        public virtual DbSet<MENU_ITEM_GROUPS> MENU_ITEM_GROUPS { get; set; }
        public virtual DbSet<MENU_ITEM_GROUPS_MAP> MENU_ITEM_GROUPS_MAP { get; set; }
        public virtual DbSet<MS_DINING_EMAILS> MS_DINING_EMAILS { get; set; }
        public virtual DbSet<REVOLVING_STATION_ITEMS> REVOLVING_STATION_ITEMS { get; set; }
        public virtual DbSet<WEATHER_TRACK> WEATHER_TRACK { get; set; }
        public virtual DbSet<EmployeeList> EmployeeLists { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<BusinessGroup> BusinessGroups { get; set; }
        public virtual DbSet<Cafe> Cafes { get; set; }
        public virtual DbSet<CostCenter> CostCenters { get; set; }
        public virtual DbSet<LinesOfBusiness> LinesOfBusinesses { get; set; }
        public virtual DbSet<Market> Markets { get; set; }
        public virtual DbSet<Population> Populations { get; set; }
        public virtual DbSet<PopulationAllocation> PopulationAllocations { get; set; }
        public virtual DbSet<ApplicationSession> ApplicationSessions { get; set; }
        public virtual DbSet<Building_Date> Building_Date { get; set; }
        public virtual DbSet<CafeList> CafeLists { get; set; }
        public virtual DbSet<COFFEE_CONCEPTS> COFFEE_CONCEPTS { get; set; }
        public virtual DbSet<FLASHBOARD_VISUAL_CATEGORIES> FLASHBOARD_VISUAL_CATEGORIES { get; set; }
        public virtual DbSet<MENU_ITEM_MAPPINGS> MENU_ITEM_MAPPINGS { get; set; }
        public virtual DbSet<POS_ID_MAPPINGS> POS_ID_MAPPINGS { get; set; }
        public virtual DbSet<REVOLVING_STATION_DATES> REVOLVING_STATION_DATES { get; set; }
        public virtual DbSet<StationList> StationLists { get; set; }
    }
}
