//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessGroup
    {
        public long PID { get; set; }
        public string BusinessGroup1 { get; set; }
        public string GroupLeader { get; set; }
        public long LOB { get; set; }
    }
}
