//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CafeList
    {
        public int CafeID { get; set; }
        public string CafeName { get; set; }
        public string CafeHours { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string StateName { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string Phone { get; set; }
        public string Campus { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public string PictureURL { get; set; }
    }
}
