//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class COFFEE_CONCEPTS
    {
        public int profit_center_id { get; set; }
        public string profit_center_name { get; set; }
        public string coffee_concept { get; set; }
        public string coffee_concept2 { get; set; }
        public Nullable<System.DateTime> Concept2_Date { get; set; }
    }
}
