//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATE
    {
        public int Busines { get; set; }
        public System.DateTime Date_ID { get; set; }
        public short MS_FY { get; set; }
        public byte MS_Quarter { get; set; }
        public byte MS_Period { get; set; }
        public int CG_FY { get; set; }
        public byte CG_Quarter { get; set; }
        public byte CG_Period { get; set; }
        public int Week { get; set; }
        public string Weekend_Holiday_Flag { get; set; }
        public bool IS_WEEKEND_HOLIDAY { get; set; }
    }
}
