//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOA
    {
        public long PID { get; set; }
        public Nullable<long> PersNumber { get; set; }
        public string CostCenter { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> Pending { get; set; }
        public Nullable<byte> Approved { get; set; }
        public Nullable<byte> Closed { get; set; }
        public Nullable<byte> Parental { get; set; }
        public Nullable<byte> Intermittent { get; set; }
        public Nullable<byte> Continuous { get; set; }
    }
}
