//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterBuildingList
    {
        public long PID { get; set; }
        public string BuildingName { get; set; }
        public string MSCampus { get; set; }
        public string ParticipationCampus { get; set; }
        public int TotalSeats { get; set; }
        public long SqFt { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Long { get; set; }
    }
}
