//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_ITEM_MAPPINGS
    {
        public string internal_menu_item_name { get; set; }
        public int menu_item_id { get; set; }
        public int internal_menu_item_id { get; set; }
    }
}
