//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occurrence
    {
        public long PID { get; set; }
        public Nullable<long> PersNumber { get; set; }
        public string CostCenter { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Notes { get; set; }
        public string AttendanceViolation { get; set; }
    }
}
