//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_ID_MAPPINGS
    {
        public string station_name { get; set; }
        public bool is_rotation { get; set; }
        public int prod_class_id { get; set; }
        public int new_pos_id { get; set; }
        public Nullable<int> old_pos_id { get; set; }
        public string menu_item_name { get; set; }
    }
}
