//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVOLVING_STATION_ITEMS
    {
        public int ID { get; set; }
        public string concept_name { get; set; }
        public int prod_class_id { get; set; }
        public int menu_item_id { get; set; }
    
        public virtual REVOLVING_STATION_ITEMS REVOLVING_STATION_ITEMS1 { get; set; }
        public virtual REVOLVING_STATION_ITEMS REVOLVING_STATION_ITEMS2 { get; set; }
    }
}
