//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationList
    {
        public int StationID { get; set; }
        public string StationName { get; set; }
        public string StationLogoURL { get; set; }
        public string StationNutritionURL { get; set; }
    }
}
