//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEATHER_TRACK
    {
        public System.DateTime Date { get; set; }
        public Nullable<int> MaxTemp { get; set; }
        public Nullable<int> MeanTemp { get; set; }
        public Nullable<int> MinTemp { get; set; }
        public Nullable<int> MaxDew { get; set; }
        public Nullable<int> MeanDew { get; set; }
        public Nullable<int> MinDew { get; set; }
        public Nullable<int> MaxHumid { get; set; }
        public Nullable<int> MeanHumid { get; set; }
        public Nullable<int> MinHumid { get; set; }
        public Nullable<decimal> MaxSeaLevel { get; set; }
        public Nullable<decimal> MeanSeaLevel { get; set; }
        public Nullable<decimal> MinSeaLevel { get; set; }
        public Nullable<int> MaxVisibility { get; set; }
        public Nullable<int> MeanVisibility { get; set; }
        public Nullable<int> MinVisibility { get; set; }
        public Nullable<int> MaxWindSpeed { get; set; }
        public Nullable<int> MeanWindSpeed { get; set; }
        public Nullable<int> MaxGust { get; set; }
        public Nullable<decimal> Precip { get; set; }
        public Nullable<int> CloudCover { get; set; }
        public string Events { get; set; }
        public Nullable<int> WindDirection { get; set; }
    }
}
