//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp.Entity_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AGNESEntity : DbContext
    {
        public AGNESEntity()
            : base("name=AGNESEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CashHandle> CashHandles { get; set; }
        public virtual DbSet<LOA> LOAs { get; set; }
        public virtual DbSet<Occurrence> Occurrences { get; set; }
    }
}
