//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building_Date
    {
        public int Building_DateID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public string Building { get; set; }
        public Nullable<int> HomeID { get; set; }
        public string Home { get; set; }
        public Nullable<int> DateID { get; set; }
        public Nullable<int> FMonthID { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<int> BadgeCount { get; set; }
        public Nullable<int> SwipeCount { get; set; }
        public Nullable<int> FirstCount { get; set; }
    }
}
