//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public long PID { get; set; }
        public string BldgName { get; set; }
        public long SqFt { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
        public string MSCampus { get; set; }
        public string MSNeighborhood { get; set; }
        public string ParticipationCampus { get; set; }
        public string ParticipationNeighborhood { get; set; }
        public Nullable<bool> AllowFoodTrucks { get; set; }
    }
}
