//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMONS_LOCATIONS
    {
        public int profit_center_id { get; set; }
        public string profit_center_name { get; set; }
        public string Group { get; set; }
        public string Vendor { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> SqFt_Utilized { get; set; }
        public string image_URL { get; set; }
    }
}
