//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter
    {
        public long PID { get; set; }
        public long CostCenter1 { get; set; }
        public long BusinessGroup { get; set; }
        public Nullable<long> SubUnitOf { get; set; }
        public string UnitName { get; set; }
        public string FlashName { get; set; }
        public Nullable<long> FlashTemplate { get; set; }
        public string HRUnitName { get; set; }
        public bool HRAuditable { get; set; }
    }
}
