//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeList
    {
        public long PID { get; set; }
        public string PersonnelArea { get; set; }
        public string PSubArea { get; set; }
        public string PersonnelSubArea { get; set; }
        public string RegionName { get; set; }
        public string DistrictManager { get; set; }
        public long CostCenterNumber { get; set; }
        public string CostCenter { get; set; }
        public long PersNumber { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public string NickName { get; set; }
        public string EmployeeSubGroup { get; set; }
        public long Job { get; set; }
        public string Position { get; set; }
        public Nullable<int> PSGroup { get; set; }
        public string Crcy { get; set; }
        public System.DateTime DateOfHire { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string RacialCat1 { get; set; }
        public string RacialCat2 { get; set; }
        public string RacialCat3 { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string SecondAddressLine { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
    }
}
