//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPRESSO_TERMINALS
    {
        public long PID { get; set; }
        public long Term_ID { get; set; }
        public long Profit_Center_ID { get; set; }
    }
}
