//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public int profit_center_id { get; set; }
        public string profit_center_name { get; set; }
        public string Unit { get; set; }
        public string Group { get; set; }
        public int Unit_Number { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP_Code { get; set; }
        public string DM { get; set; }
        public Nullable<long> FlashType { get; set; }
        public Nullable<long> TotalSqFt { get; set; }
        public Nullable<long> BOHSqFt { get; set; }
        public Nullable<long> FOHSqFt { get; set; }
        public Nullable<long> EspressoSqFt { get; set; }
        public string MSNeighborhood { get; set; }
        public string ParticipationNeighborhood { get; set; }
    }
}
