//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public long PID { get; set; }
        public long CostCenter { get; set; }
        public long BldgId { get; set; }
        public long ProfitCenterId { get; set; }
        public Nullable<long> SubUnitOfCafe { get; set; }
        public string Manager { get; set; }
        public string DistrictManager { get; set; }
        public int SqFt { get; set; }
    }
}
