//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_ITEM_GROUPS_MAP
    {
        public int MENU_ITEM_GROUPS_ID { get; set; }
        public int menu_item_id { get; set; }
        public int multiplier { get; set; }
    }
}
