//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGNESCSharp.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsUsers_Join
    {
        public long PID { get; set; }
        public long UnitNumber { get; set; }
        public long UserId { get; set; }
        public Nullable<bool> Delegate { get; set; }
        public Nullable<long> DelegateAddedBy { get; set; }
    }
}
