'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AGNESSharedDataEntity
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AGNESSharedDataEntity")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AccessLevels() As DbSet(Of AccessLevel)
    Public Overridable Property ModuleGroups() As DbSet(Of ModuleGroup)
    Public Overridable Property Modules() As DbSet(Of [Module])
    Public Overridable Property ModulesUsers_Join() As DbSet(Of ModulesUsers_Join)
    Public Overridable Property Users() As DbSet(Of User)
    Public Overridable Property FlashTypes() As DbSet(Of FlashType)
    Public Overridable Property FlashTypesUsers_Join() As DbSet(Of FlashTypesUsers_Join)
    Public Overridable Property UnitsSubunits() As DbSet(Of UnitsSubunit)
    Public Overridable Property UnitsUsers_Join() As DbSet(Of UnitsUsers_Join)
    Public Overridable Property NotificationConfirms() As DbSet(Of NotificationConfirm)
    Public Overridable Property Notifications() As DbSet(Of Notification)

End Class
