'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AGNESSharedData
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AGNESSharedData")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AccessLevelLists() As DbSet(Of AccessLevelList)
    Public Overridable Property ModuleGroupLists() As DbSet(Of ModuleGroupList)
    Public Overridable Property ModuleLists() As DbSet(Of ModuleList)
    Public Overridable Property ModuleUser_Join() As DbSet(Of ModuleUser_Join)
    Public Overridable Property UnitUser_Join() As DbSet(Of UnitUser_Join)
    Public Overridable Property UserLists() As DbSet(Of UserList)

End Class
