'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AssociateShortage
    Public Property PID As Long
    Public Property UnitNumber As Long
    Public Property [Date] As Date
    Public Property HourlyOut As Integer
    Public Property SalaryOut As Integer

End Class
