'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Availability
    Public Property PID As Long
    Public Property VendorID As Long
    Public Property Monday As Short
    Public Property Tuesday As Short
    Public Property Wednesday As Short
    Public Property Thursday As Short
    Public Property Friday As Short

End Class
