'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Building
    Public Property PID As Long
    Public Property BldgName As String
    Public Property SqFt As Long
    Public Property Lat As Decimal
    Public Property [Long] As Decimal
    Public Property MSCampus As String
    Public Property MSNeighborhood As String
    Public Property ParticipationCampus As String
    Public Property ParticipationNeighborhood As String
    Public Property AllowFoodTrucks As Nullable(Of Boolean)

End Class
