'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BusinessGroup
    Public Property PID As Long
    Public Property BusinessGroupName As String
    Public Property GroupOverview As String
    Public Property Headcount As Nullable(Of Integer)
    Public Property WorkTimes As Nullable(Of Integer)
    Public Property OnsiteRemote As Nullable(Of Integer)
    Public Property OrgLeader As Integer
    Public Property RelMgr As Nullable(Of Integer)
    Public Property Revenue As Nullable(Of Decimal)
    Public Property Events As Nullable(Of Integer)
    Public Property Events500 As Nullable(Of Integer)
    Public Property EventsCatered As Nullable(Of Integer)
    Public Property OffsiteSpend As Nullable(Of Decimal)

End Class
