'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BGCRMEntity
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BGCRMEntity")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property BusinessGroups() As DbSet(Of BusinessGroup)
    Public Overridable Property Comm_Join() As DbSet(Of Comm_Join)
    Public Overridable Property Communications() As DbSet(Of Communication)
    Public Overridable Property Culture_Join() As DbSet(Of Culture_Join)
    Public Overridable Property EventSpaces() As DbSet(Of EventSpace)
    Public Overridable Property EventTypes() As DbSet(Of EventType)
    Public Overridable Property FreqCust_Join() As DbSet(Of FreqCust_Join)
    Public Overridable Property FrequentCustomers() As DbSet(Of FrequentCustomer)
    Public Overridable Property GroupCultures() As DbSet(Of GroupCulture)
    Public Overridable Property Involvements() As DbSet(Of Involvement)
    Public Overridable Property Involvement_Join() As DbSet(Of Involvement_Join)
    Public Overridable Property Leaders() As DbSet(Of Leader)
    Public Overridable Property Leaders_Join() As DbSet(Of Leaders_Join)
    Public Overridable Property Locations_Join() As DbSet(Of Locations_Join)
    Public Overridable Property NotableEvents() As DbSet(Of NotableEvent)
    Public Overridable Property NotableEvents_Join() As DbSet(Of NotableEvents_Join)
    Public Overridable Property OffsiteLocations() As DbSet(Of OffsiteLocation)
    Public Overridable Property Offsites_Join() As DbSet(Of Offsites_Join)
    Public Overridable Property Planners() As DbSet(Of Planner)
    Public Overridable Property Planners_Join() As DbSet(Of Planners_Join)
    Public Overridable Property Refresh_Join() As DbSet(Of Refresh_Join)
    Public Overridable Property RefreshEvents() As DbSet(Of RefreshEvent)
    Public Overridable Property TopEventTypes_Join() As DbSet(Of TopEventTypes_Join)
    Public Overridable Property TopSpaces_Join() As DbSet(Of TopSpaces_Join)
    Public Overridable Property WorkLocations() As DbSet(Of WorkLocation)
    Public Overridable Property WorkTimes() As DbSet(Of WorkTime)
    Public Overridable Property Locations() As DbSet(Of Location)

End Class
