'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BGCRMEntity
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BGCRMEntity")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Communications() As DbSet(Of Communications)
    Public Overridable Property Cultures() As DbSet(Of Cultures)
    Public Overridable Property Customers() As DbSet(Of Customers)
    Public Overridable Property Groups() As DbSet(Of Group)
    Public Overridable Property GroupsCommunications_Join() As DbSet(Of GroupsCommunications_Join)
    Public Overridable Property GroupsCultures_Join() As DbSet(Of GroupsCultures_Join)
    Public Overridable Property GroupsCustomers_Join() As DbSet(Of GroupsCustomers_Join)
    Public Overridable Property GroupsEvents_Join() As DbSet(Of GroupsEvents_Join)
    Public Overridable Property GroupsInvolvements_Join() As DbSet(Of GroupsInvolvements_Join)
    Public Overridable Property GroupsLeaders_Join() As DbSet(Of GroupsLeaders_Join)
    Public Overridable Property GroupsLocations_Join() As DbSet(Of GroupsLocations_Join)
    Public Overridable Property GroupsNotableEvents_Join() As DbSet(Of GroupsNotableEvents_Join)
    Public Overridable Property GroupsOffsiteLocations_Join() As DbSet(Of GroupsOffsiteLocations_Join)
    Public Overridable Property GroupsPlanners_Join() As DbSet(Of GroupsPlanners_Join)
    Public Overridable Property GroupsSpaces_Join() As DbSet(Of GroupsSpaces_Join)
    Public Overridable Property Involvements() As DbSet(Of Involvements)
    Public Overridable Property Leaders() As DbSet(Of Leaders)
    Public Overridable Property NotableEvents() As DbSet(Of NotableEvents)
    Public Overridable Property OffsiteLocations() As DbSet(Of OffsiteLocations)
    Public Overridable Property Planners() As DbSet(Of Planners)
    Public Overridable Property RefreshEventOrigins() As DbSet(Of RefreshEventOrigin)
    Public Overridable Property RefreshEvents() As DbSet(Of RefreshEvents)
    Public Overridable Property Spaces() As DbSet(Of Spaces)
    Public Overridable Property WorkLocations() As DbSet(Of WorkLocation)
    Public Overridable Property WorkTimes() As DbSet(Of WorkTime)
    Public Overridable Property Events() As DbSet(Of Events)

End Class
