'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cafe
    Public Property PID As Long
    Public Property CostCenter As Long
    Public Property BldgId As Long
    Public Property ProfitCenterId As Long
    Public Property Manager As String
    Public Property DistrictManager As String
    Public Property HasHood As Nullable(Of Boolean)
    Public Property AnchorStationFoodType As Nullable(Of Long)
    Public Property AnchorStationFoodSubType As Nullable(Of Long)
    Public Property BrandStations As Short
    Public Property SqFt As Integer
    Public Property FOHSqFt As Integer
    Public Property BOHSqFt As Integer
    Public Property EspressoSqFt As Integer

End Class
