'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contact
    Public Property PID As Long
    Public Property VendorID As Long
    Public Property PrimaryContact As Nullable(Of Boolean)
    Public Property Title As String
    Public Property Name As String
    Public Property Phone As String
    Public Property Email As String

End Class
