'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CostCenter
    Public Property PID As Long
    Public Property CostCenter1 As Long
    Public Property BusinessGroup As Long
    Public Property SubUnitOf As Nullable(Of Long)
    Public Property UnitName As String
    Public Property FlashName As String
    Public Property FlashTemplate As Nullable(Of Long)
    Public Property HRUnitName As String
    Public Property HRAuditable As Boolean

End Class
