'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Dates
    Public Property Busines As Integer
    Public Property Date_ID As Date
    Public Property MS_FY As Short
    Public Property MS_Quarter As Byte
    Public Property MS_Period As Byte
    Public Property CG_FY As Integer
    Public Property CG_Quarter As Byte
    Public Property CG_Period As Byte
    Public Property Week As Integer
    Public Property Weekend_Holiday_Flag As String
    Public Property IS_WEEKEND_HOLIDAY As Boolean

End Class
