'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmployeeList
    Public Property PID As Long
    Public Property PersonnelArea As String
    Public Property PSubArea As String
    Public Property PersonnelSubArea As String
    Public Property RegionName As String
    Public Property DistrictManager As String
    Public Property CostCenterNumber As Long
    Public Property CostCenter As String
    Public Property PersNumber As Long
    Public Property LastName As String
    Public Property MiddleName As String
    Public Property FirstName As String
    Public Property NickName As String
    Public Property EmployeeSubGroup As String
    Public Property Job As Long
    Public Property Position As String
    Public Property PSGroup As Nullable(Of Integer)
    Public Property Crcy As String
    Public Property DateOfHire As Date
    Public Property BirthDate As Nullable(Of Date)
    Public Property RacialCat1 As String
    Public Property RacialCat2 As String
    Public Property RacialCat3 As String
    Public Property Gender As String
    Public Property Address As String
    Public Property SecondAddressLine As String
    Public Property City As String
    Public Property State As String
    Public Property Zip As String
    Public Property Telephone As String
    Public Property Email As String

End Class
