'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FlashActualData
    Public Property PID As Long
    Public Property MSFY As Short
    Public Property MSP As Byte
    Public Property Week As Byte
    Public Property UnitNumber As Long
    Public Property Status As String
    Public Property GL As Long
    Public Property GLCategory As String
    Public Property FlashValue As Decimal
    Public Property FlashNotes As String
    Public Property OpDaysWeek As Byte
    Public Property OpDaysPeriod As Byte
    Public Property SavedBy As String

End Class
