'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BIEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BIEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property MasterBuildingLists() As DbSet(Of MasterBuildingList)
    Public Overridable Property Dates() As DbSet(Of Dates)
    Public Overridable Property LOCATIONS() As DbSet(Of LOCATION)
    Public Overridable Property EmployeeLists() As DbSet(Of EmployeeList)
    Public Overridable Property ApplicationSessions() As DbSet(Of ApplicationSession)
    Public Overridable Property Buildings() As DbSet(Of Building)
    Public Overridable Property BusinessGroups() As DbSet(Of BusinessGroup)
    Public Overridable Property Cafes() As DbSet(Of Cafe)
    Public Overridable Property CostCenters() As DbSet(Of CostCenter)
    Public Overridable Property LinesOfBusinesses() As DbSet(Of LinesOfBusiness)
    Public Overridable Property Markets() As DbSet(Of Market)
    Public Overridable Property Populations() As DbSet(Of Population)
    Public Overridable Property PopulationAllocations() As DbSet(Of PopulationAllocation)

End Class
