'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KPIWithholdingType
    Public Property PID As Long
    Public Property WithholdingType As String

    Public Overridable Property VendorInfoes As ICollection(Of VendorInfo) = New HashSet(Of VendorInfo)

End Class
