'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LOA
    Public Property PID As Long
    Public Property PersNumber As Nullable(Of Long)
    Public Property CostCenter As String
    Public Property LastName As String
    Public Property FirstName As String
    Public Property Type As String
    Public Property DateStart As Nullable(Of Date)
    Public Property DateEnd As Nullable(Of Date)
    Public Property Notes As String
    Public Property Pending As Nullable(Of Byte)
    Public Property Approved As Nullable(Of Byte)
    Public Property Closed As Nullable(Of Byte)
    Public Property Parental As Nullable(Of Byte)
    Public Property Intermittent As Nullable(Of Byte)
    Public Property Continuous As Nullable(Of Byte)

End Class
