'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Location
    Public Property PID As Long
    Public Property BuildingName As String
    Public Property MSCampus As String
    Public Property ParticipationCampus As String
    Public Property TotalSeats As Nullable(Of Integer)
    Public Property SqFt As Nullable(Of Integer)
    Public Property Lat As Nullable(Of Decimal)
    Public Property Lng As Nullable(Of Decimal)

End Class
