'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Location
    Public Property PID As Long
    Public Property BuildingName As String
    Public Property Campus As Nullable(Of Integer)
    Public Property Population As Nullable(Of Long)

End Class
