'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LOCATION
    Public Property profit_center_id As Integer
    Public Property profit_center_name As String
    Public Property Unit As String
    Public Property Group As String
    Public Property Unit_Number As Integer
    Public Property Latitude As Nullable(Of Decimal)
    Public Property Longitude As Nullable(Of Decimal)
    Public Property Address As String
    Public Property City As String
    Public Property State As String
    Public Property ZIP_Code As String
    Public Property DM As String
    Public Property FlashType As Nullable(Of Byte)
    Public Property TotalSqFt As Nullable(Of Long)
    Public Property BOHSqFt As Nullable(Of Long)
    Public Property FOHSqFt As Nullable(Of Long)
    Public Property EspressoSqFt As Nullable(Of Long)
    Public Property MSNeighborhood As String
    Public Property ParticipationNeighborhood As String

End Class
