'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Market
    Public Property PID As Long
    Public Property CostCenter As Long
    Public Property BldgId As Long
    Public Property ProfitCenterId As Long
    Public Property SubUnitOfCafe As Nullable(Of Long)
    Public Property Manager As String
    Public Property DistrictManager As String
    Public Property SqFt As Integer

End Class
