'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NotableEvent
    Public Property PID As Long
    Public Property EventName As String
    Public Property DateStart As Date
    Public Property DateEnd As Date
    Public Property RecurringEvent As Byte

End Class
