'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Notification
    Public Property PID As Long
    Public Property StartDate As Date
    Public Property EndDate As Date
    Public Property Audience As Long
    Public Property Message As String
    Public Property Creator As Long
    Public Property OneOffNotification As Boolean
    Public Property Snooze As Boolean
    Public Property RequireConfirm As Boolean
    Public Property ActionPoint As String

End Class
