'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PopulationAllocation
    Public Property PID As Long
    Public Property CafeId As Long
    Public Property AllocatedBldg As Long
    Public Property Allocation As Decimal

End Class
