'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product_Class_Master
    Public Property ent_id As Integer
    Public Property prod_class_id As Integer
    Public Property prod_class_name As String
    Public Property default_rev_cat_id As Nullable(Of Integer)
    Public Property default_tax_grp_id As Nullable(Of Integer)
    Public Property default_sec_id As Nullable(Of Integer)
    Public Property default_menu_item_group_id As Nullable(Of Integer)
    Public Property default_rpt_cat_id As Nullable(Of Integer)
    Public Property store_id As Integer
    Public Property item_restricted_flag As Boolean

End Class
