'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ReceivedCAMCheck
    Public Property PID As Long
    Public Property VID As Long
    Public Property VendorName As String
    Public Property CheckNumber As String
    Public Property DepositDate As Date
    Public Property DayofWeek As Short
    Public Property CheckAmount As Decimal
    Public Property CheckNotes As String

End Class
