'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RefreshEvent
    Public Property PID As Long
    Public Property EventID As Nullable(Of Long)
    Public Property EventName As String
    Public Property BusinessGroupId As Integer
    Public Property MoveStartDate As Date
    Public Property MoveEndDate As Date
    Public Property PopulationMoving As Long
    Public Property Destination As String

End Class
