'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RefreshEventOrigin
    Public Property PID As Long
    Public Property EventId As Long
    Public Property BuildingId As Long
    Public Property PopMoving As Long
    Public Property BusinessGroupID As Long

End Class
