'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Schedule
    Public Property PID As Long
    Public Property ScheduleDate As Date
    Public Property Location As String
    Public Property Station As String
    Public Property SavedBy As String
    Public Property VendorId As Long

End Class
