'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SickOtRecord
    Public Property PID As Long
    Public Property UnitNumber As Long
    Public Property MSFY As Short
    Public Property MSP As Byte
    Public Property Week As Byte
    Public Property SickPay As Decimal
    Public Property OtPay As Decimal

End Class
