'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TrainingType
    Public Property PID As Long
    Public Property LOB As String
    Public Property TrainingName As String
    Public Property TrainingDescription As String
    Public Property Hours As Decimal
    Public Property Certification As Nullable(Of Boolean)
    Public Property Scored As Nullable(Of Boolean)

End Class
