'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UnitsSubunit
    Public Property PID As Long
    Public Property UnitNumber As Long
    Public Property SubUnitNumber As Long
    Public Property Description As String
    Public Property Grouping As String

End Class
