'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UnitsUsers_Join
    Public Property PID As Long
    Public Property UnitNumber As Long
    Public Property UserId As Long
    Public Property [Delegate] As Boolean
    Public Property DelegateAddedBy As Nullable(Of Long)

End Class
