'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserList
    Public Property PID As Long
    Public Property UserName As String
    Public Property UserAlias As String
    Public Property FirstName As String
    Public Property LastName As String
    Public Property SpokenName As String
    Public Property AccessLevelId As Long
    Public Property DateAdded As Date
    Public Property AddedBy As String

End Class
