'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class VendorEntity
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=VendorEntity")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Availabilities() As DbSet(Of Availability)
    Public Overridable Property CAMWithholdings() As DbSet(Of CAMWithholding)
    Public Overridable Property Contacts() As DbSet(Of Contact)
    Public Overridable Property FoodSubTypes() As DbSet(Of FoodSubType)
    Public Overridable Property FoodTypes() As DbSet(Of FoodType)
    Public Overridable Property KPIWithholdings() As DbSet(Of KPIWithholding)
    Public Overridable Property ProfitCenters() As DbSet(Of ProfitCenter)
    Public Overridable Property ReceivedCAMChecks() As DbSet(Of ReceivedCAMCheck)
    Public Overridable Property VendorInfo() As DbSet(Of VendorInfo)

End Class
