'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class WCREntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=WCREntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property GLsTenders_Join() As DbSet(Of GLsTenders_Join)
    Public Overridable Property Tenders() As DbSet(Of Tenders)
    Public Overridable Property CAMWithholdings() As DbSet(Of CAMWithholdings)
    Public Overridable Property KPIWithholdings() As DbSet(Of KPIWithholdings)
    Public Overridable Property ReceivedCAMChecks() As DbSet(Of ReceivedCAMChecks)
    Public Overridable Property VendorInfo() As DbSet(Of VendorInfo)

End Class
